# Generated by Django 5.1.6 on 2025-05-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaludApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='diagnostico_tratamiento',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='diagnostico',
            field=models.TextField(default='Testing diagnostico...', verbose_name='Diagnóstico médico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='tratamiento',
            field=models.TextField(default='Testing tratamiento...', verbose_name='Tratamiento indicado'),
            preserve_default=False,
        ),
    ]
