# Generated by Django 5.1.6 on 2025-05-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaludApp', '0003_visita_diagnostico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='diagnostico',
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='visita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='SaludApp.visita', verbose_name='Visita'),
        ),
    ]
