# Generated by Django 5.1.6 on 2025-06-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaludApp', '0004_remove_visita_diagnostico_alter_diagnostico_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciónes adicionales'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='diagnostico',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico médico'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='tratamiento',
            field=models.TextField(blank=True, null=True, verbose_name='Tratamiento indicado'),
        ),
    ]
